version: "3.9"
services:
  execution:
    tty: true
    environment:
    - TERM=xterm-256color
    - COLORTERM=truecolor
    stop_grace_period: 30s
    container_name: sedge-execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    networks:
    - sedge
    volumes:
    - ${EC_DATA_DIR}:/nethermind/data
    - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
    - 30303:30303/tcp
    - 30303:30303/udp
    - 8008:8008
    - 8545:8545
    - 8551:8551
    expose:
    - 8545
    - 8551
    command:
    - --config=${NETWORK}
    - --datadir=/nethermind/data
    - --log=${NETHERMIND_LOG_LEVEL}
    - --JsonRpc.Enabled=true
    - --JsonRpc.Host=0.0.0.0
    - --JsonRpc.Port=8545
    - --JsonRpc.JwtSecretFile=/tmp/jwt/jwtsecret
    - --JsonRpc.EngineHost=0.0.0.0
    - --JsonRpc.EnginePort=8551
    - --Network.DiscoveryPort=30303
    - --HealthChecks.Enabled=true
    - --Metrics.Enabled=true
    - --Metrics.ExposePort=8008
    - --Sync.NonValidatorNode=true
    - --Sync.DownloadBodiesInFastSync=false
    - --Sync.DownloadReceiptsInFastSync=false
    - --JsonRpc.EnabledModules=[Eth,TxPool,Web3,Net,Health,Rpc,Debug,Trace]
  consensus:
    stop_grace_period: 30s
    container_name: sedge-consensus-client
    restart: unless-stopped
    image: ${CC_IMAGE_VERSION}
    networks:
    - sedge
    volumes:
    - ${CC_DATA_DIR}:/var/lib/lighthouse
    - ${CC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
    - 9000:9000/tcp
    - 9000:9000/udp
    - 5054:5054/tcp
    - 4000:4000
    expose:
    - 4000
    command:
    - lighthouse
    - bn
    - --disable-upnp
    - --datadir=/var/lib/lighthouse
    - --port=9000
    - --http
    - --http-address=0.0.0.0
    - --http-port=4000
    - --network=${NETWORK}
    - --target-peers=${CC_PEER_COUNT}
    - --execution-endpoints=${EC_AUTH_URL}
    - --execution-jwt=/tmp/jwt/jwtsecret
    - --eth1=${EC_API_URL}
    - --debug-level=${CC_LOG_LEVEL}
    - --validator-monitor-auto
    - --subscribe-all-subnets
    - --import-all-attestations
    - --metrics
    - --metrics-port=5054
    - --metrics-address=0.0.0.0
    - --checkpoint-sync-url=http://139.144.26.89:4000/
networks:
  sedge:
    name: sedge-network
